### ISSUE TITLE
vox2schematic - TypeError: to_nbt() takes 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by hellocatfood** [Voxelers/mcthings#140]
I'm trying to run vox2schematic on this model https://github.com/mikelovesrobots/mmmm/blob/master/vox/alien_crawl1.vox (also on my own models). Running it gives me this error:
```
ox2schematic alien_crawl1.vox 
2021-03-13 17:35:33,411 Vox input file: alien_crawl1.vox
2021-03-13 17:35:33,411 Schematic output file: alien_crawl1.schematic
2021-03-13 17:35:33,412 Material data not found
Traceback (most recent call last):
  File "/home/hellocatfood/.local/bin/vox2schematic", line 71, in <module>
    main()
  File "/home/hellocatfood/.local/bin/vox2schematic", line 62, in main
    voxels._blocks_memory.to_schematic(schematic_file)
  File "/home/hellocatfood/.local/lib/python3.8/site-packages/mcthings/blocks_memory.py", line 254, in to_schematic
    self.build_schematic().write_file(file_path)
  File "/home/hellocatfood/.local/lib/python3.8/site-packages/mcthings/blocks_memory.py", line 244, in build_schematic
    return self.to_nbt(init_pos, end_pos, self)
TypeError: to_nbt() takes 3 positional arguments but 4 were given
```

I'm using python3.8 on Ubuntu 20.04

**Comment by ErsteNacht** [comment]
I got the same problem. I decided to try older versions and one of them worked.

pip install mcthings==0.51.4
